import { db } from "./db";
import { stories, chapters, questions } from "@shared/schema";
import { eq } from "drizzle-orm";

// Bloom level assignment for the 49 questions based on cognitive level
const bloomMap: Record<number, string> = {
  1: "remember", 10: "remember", 11: "remember", 20: "remember", 40: "remember", 43: "remember",
  2: "understand", 7: "understand", 9: "understand", 12: "understand", 18: "understand", 41: "understand",
  5: "apply", 6: "apply", 15: "apply", 21: "apply", 23: "apply", 28: "apply",
  31: "apply", 32: "apply", 33: "apply", 39: "apply", 42: "apply",
  19: "analyze", 25: "analyze", 26: "analyze", 34: "analyze", 35: "analyze", 45: "analyze", 46: "analyze",
  13: "evaluate", 24: "evaluate", 27: "evaluate", 29: "evaluate", 30: "evaluate", 37: "evaluate", 47: "evaluate", 49: "evaluate",
  3: "create", 4: "create", 8: "create", 14: "create", 16: "create", 17: "create",
  22: "create", 36: "create", 38: "create", 44: "create", 48: "create",
};

// Question data from chapter-8001-4
const questionData = [
  { id: 1, type: "multiple-choice", text: "Stop signs are shaped as octagons because:", options: { choices: ["They're easier to make than circles", "The unique shape is recognizable even when partially covered or at night", "Octagons use less material than circles", "They're less likely to roll away if knocked down"] }, answer: "b", theme: "math", difficulty: "easy", tags: ["GEOMETRY", "REAL-WORLD SHAPES", "CRITICAL THINKING", "EVERYDAY MATH"], hints: ["Think about why shape matters for safety.", "Consider what happens at night or when a sign is dirty.", "The answer is about visibility and recognition."], explanation: "Octagonal shape is unique among road signs, making stop signs recognizable even when partially obscured." },
  { id: 2, type: "matching", text: "Match the Shape with its real-world example from Ethan's walk:", options: { items: [{ item: "Triangle", match: "Roof" }, { item: "Rhombus", match: "Construction warning sign" }, { item: "Pentagon", match: "School zone sign" }, { item: "Octagon", match: "Stop sign" }] }, answer: ["Triangle:Roof", "Rhombus:Construction warning sign", "Pentagon:School zone sign", "Octagon:Stop sign"], theme: "math", difficulty: "easy", tags: ["GEOMETRY", "SHAPE RECOGNITION", "VISUAL MATCHING", "SPATIAL REASONING"], hints: ["Think about signs you see on the road.", "A stop sign has 8 sides.", "School zone signs have 5 sides."], explanation: "Each shape corresponds to a common real-world object Ethan encountered." },
  { id: 3, type: "unscramble", text: "Unscramble these geometric shapes Ethan observed:", options: { letters: "ARITGNEL,SOBMURH,NOGACOT,GANONTEP" }, answer: ["TRIANGLE", "RHOMBUS", "OCTAGON", "PENTAGON"], theme: "math", difficulty: "medium", tags: ["GEOMETRY", "VOCABULARY", "WORD DECODING", "SPELLING"], hints: ["The first word is a 3-sided shape.", "The second word is like a diamond.", "Try rearranging the letters to find shape names."], explanation: "These are geometric shapes: Triangle, Rhombus, Octagon, Pentagon." },
  { id: 4, type: "hidden-word", text: "Find four geometric shapes from the story hidden in this grid:", options: { grid: ["TRIANGLEOP", "QZXCNMLCE", "RHOMBUSKTN", "SDFGHUJKA", "OCTAGONLGT", "PENTAGONOA", "QWERTYUING", "ASDFGHJKLO"], words: ["TRIANGLE", "RHOMBUS", "OCTAGON", "PENTAGON"] }, answer: ["TRIANGLE", "RHOMBUS", "OCTAGON", "PENTAGON"], theme: "math", difficulty: "medium", tags: ["GEOMETRY", "VISUAL PERCEPTION", "WORD SEARCH", "ATTENTION TO DETAIL"], hints: ["Look for words going left to right.", "Start from the first letter of each row.", "The shapes are: Triangle, Rhombus, Octagon, Pentagon."], explanation: "The four hidden shapes are Triangle, Rhombus, Octagon, and Pentagon." },
  { id: 5, type: "multiple-choice", text: "If a roof is shaped like a triangle with a base of 8 meters and a height of 6 meters, what is its area?", options: { choices: ["14 square meters", "24 square meters", "48 square meters", "16 square meters"] }, answer: "b", theme: "math", difficulty: "medium", tags: ["GEOMETRY", "AREA CALCULATION", "TRIANGLE PROPERTIES", "STATE MATH TEST"], hints: ["Area of a triangle = (base × height) / 2.", "Multiply 8 × 6 first.", "Then divide by 2."], explanation: "Area = (8 × 6) / 2 = 24 square meters." },
  { id: 6, type: "multiple-choice", text: "As Ethan walked up the hill, his potential energy:", options: { choices: ["Decreased", "Remained the same", "Increased", "Changed to thermal energy"] }, answer: "c", theme: "science", difficulty: "medium", tags: ["PHYSICS", "ENERGY CONCEPTS", "GRAVITATIONAL POTENTIAL", "SCIENCE ASSESSMENT"], hints: ["Potential energy depends on height.", "Going up means more height.", "More height = more potential energy."], explanation: "Gravitational potential energy increases with height." },
  { id: 7, type: "matching", text: "Connect each scenario from the walk with the primary type of energy involved:", options: { items: [{ item: "Rock at the top of a hill", match: "Potential energy" }, { item: "Rock rolling down", match: "Kinetic energy" }, { item: "Wind pushing against Ethan", match: "Mechanical energy" }, { item: "Wind chimes making sound", match: "Sound energy" }] }, answer: ["Rock at the top of a hill:Potential energy", "Rock rolling down:Kinetic energy", "Wind pushing against Ethan:Mechanical energy", "Wind chimes making sound:Sound energy"], theme: "science", difficulty: "medium", tags: ["PHYSICS", "ENERGY TRANSFORMATION", "CONCEPTUAL UNDERSTANDING", "SCIENCE OLYMPIAD"], hints: ["A stationary object up high has stored energy.", "Moving objects have kinetic energy.", "Sound comes from vibrations."], explanation: "Each scenario demonstrates a different form of energy." },
  { id: 8, type: "unscramble", text: "Unscramble these physics terms Ethan used during the walk:", options: { letters: "TNEPOITAL,CKNETII,RTAISECSNE,TIORNBAVI" }, answer: ["POTENTIAL", "KINETIC", "RESISTANCE", "VIBRATION"], theme: "science", difficulty: "hard", tags: ["PHYSICS", "SCIENTIFIC TERMINOLOGY", "WORD SKILLS", "VOCABULARY BUILDING"], hints: ["The first word means stored energy.", "The second word means energy of motion.", "The third word is a force that opposes motion."], explanation: "Potential, Kinetic, Resistance, and Vibration are key physics terms." },
  { id: 9, type: "fill-blank", text: "When the rock rolls down the hill, potential energy transforms into __________ energy.", options: {}, answer: "kinetic", theme: "science", difficulty: "medium", tags: ["PHYSICS", "ENERGY CONVERSION", "CONCEPTUAL UNDERSTANDING", "SCIENCE RECALL"], hints: ["This type of energy relates to movement.", "It starts with the letter K.", "Think: energy of motion."], explanation: "Potential energy converts to kinetic energy during motion." },
  { id: 10, type: "multiple-choice", text: "Stop signs are made of metal rather than wood because metal is:", options: { choices: ["Cheaper", "More colorful", "More durable in outdoor conditions", "Easier to recycle"] }, answer: "c", theme: "materials", difficulty: "easy", tags: ["MATERIALS SCIENCE", "PROPERTIES OF MATTER", "ENGINEERING", "LOGICAL REASONING"], hints: ["Think about what happens to wood in rain.", "Metal resists weather better.", "Durability means lasting a long time."], explanation: "Metal is more durable and weather-resistant than wood for outdoor use." },
  { id: 11, type: "true-false", text: "According to the story, Ethan used a stopwatch to measure their walking time.", options: {}, answer: "false", theme: "language", difficulty: "easy", tags: ["READING COMPREHENSION", "DETAIL RECALL", "CLOSE READING", "STORY ANALYSIS"], hints: ["Think carefully about what Ethan actually used.", "Did the story mention a stopwatch specifically?", "Ethan did not use a stopwatch."], explanation: "The story does not mention Ethan using a stopwatch." },
  { id: 12, type: "matching", text: "Connect each concept from Ethan's walk with the scientific principle:", options: { items: [{ item: "Rock rolling downhill", match: "Energy conservation" }, { item: "Wind pushing against Ethan", match: "Air resistance" }, { item: "Triangular roof strength", match: "Structural stability" }, { item: "Sound from wind chimes", match: "Vibration creates sound waves" }] }, answer: ["Rock rolling downhill:Energy conservation", "Wind pushing against Ethan:Air resistance", "Triangular roof strength:Structural stability", "Sound from wind chimes:Vibration creates sound waves"], theme: "interdisciplinary", difficulty: "hard", tags: ["INTERDISCIPLINARY", "SCIENCE PRINCIPLES", "CONCEPTUAL MATCHING", "CRITICAL THINKING"], hints: ["Rolling involves energy changing forms.", "Wind creates a pushing force.", "Triangles are strong structures."], explanation: "Each observation connects to a fundamental scientific principle." },
  { id: 13, type: "multiple-choice", text: "Triangular roofs are common because:", options: { choices: ["Triangles are more attractive", "Rain or snow slides off easily and they're structurally strong", "They're cheaper to build", "They provide more attic space"] }, answer: "b", theme: "engineering", difficulty: "medium", tags: ["ENGINEERING", "STRUCTURAL DESIGN", "FUNCTIONAL REASONING", "PRACTICAL SCIENCE"], hints: ["Think about what happens when it rains or snows.", "Triangles distribute weight well.", "The answer involves both weather and strength."], explanation: "Triangular roofs shed precipitation and are structurally strong." },
  { id: 14, type: "word-sequence", text: "Place these energy transformations in the correct order for a rock rolling down a hill:", options: { wordSequence: ["Kinetic energy increases", "Rock is stationary at top of hill", "Rock comes to rest at bottom", "Potential energy decreases", "Rock starts moving"] }, answer: ["Rock is stationary at top of hill", "Rock starts moving", "Potential energy decreases", "Kinetic energy increases", "Rock comes to rest at bottom"], theme: "science", difficulty: "hard", tags: ["PHYSICS", "SEQUENTIAL REASONING", "ENERGY TRANSFORMATION", "LOGICAL ORDERING"], hints: ["Start with the rock at rest.", "The rock begins to move next.", "It ends when the rock stops at the bottom."], explanation: "The rock starts with potential energy at the top and converts it to kinetic energy as it rolls down." },
  { id: 15, type: "multiple-choice", text: "When Ethan leaned into the wind, which force was acting on him?", options: { choices: ["Gravity", "Air resistance", "Friction", "Magnetic force"] }, answer: "b", theme: "science", difficulty: "medium", tags: ["PHYSICS", "FORCES", "READING RECALL", "SCIENTIFIC TERMINOLOGY"], hints: ["The wind pushes against you.", "This force opposes movement through air.", "It starts with 'Air'."], explanation: "Air resistance (drag) is the force of wind pushing against Ethan." },
  { id: 16, type: "multiple-choice", text: "When Ethan said 'The wind is playing us a song,' this is an example of:", options: { choices: ["Simile", "Metaphor", "Personification", "Hyperbole"] }, answer: "c", theme: "language", difficulty: "medium", tags: ["LANGUAGE ARTS", "LITERARY DEVICES", "FIGURATIVE LANGUAGE", "READING COMPREHENSION"], hints: ["The wind is given a human ability.", "Playing a song is something a person does.", "Giving human qualities to non-human things is called..."], explanation: "Personification gives human qualities (playing a song) to the wind." },
  { id: 17, type: "unscramble", text: "Unscramble this literary device that Ethan specifically mentioned:", options: { letters: "FICAPORNNOSTIE" }, answer: ["PERSONIFICATION"], theme: "language", difficulty: "hard", tags: ["LANGUAGE ARTS", "LITERARY TERMINOLOGY", "VOCABULARY", "ELA SKILLS"], hints: ["It means giving human traits to non-human things.", "It has 15 letters.", "It starts with P."], explanation: "Personification is a literary device giving human qualities to non-human things." },
  { id: 18, type: "matching", text: "Connect each sentence with whether it contains personification:", options: { items: [{ item: "\"The wind howled loudly\"", match: "Contains personification" }, { item: "\"The wind moved the branches\"", match: "Doesn't contain personification" }, { item: "\"The sun smiled down on us\"", match: "Contains personification" }, { item: "\"The rain fell heavily\"", match: "Doesn't contain personification" }] }, answer: ["\"The wind howled loudly\":Contains personification", "\"The wind moved the branches\":Doesn't contain personification", "\"The sun smiled down on us\":Contains personification", "\"The rain fell heavily\":Doesn't contain personification"], theme: "language", difficulty: "medium", tags: ["LANGUAGE ARTS", "FIGURATIVE LANGUAGE", "READING ANALYSIS", "ELA ASSESSMENT"], hints: ["Does the sentence give a human action to a non-human thing?", "Howling and smiling are human actions.", "Moving branches and falling are natural actions."], explanation: "Personification uses human verbs (howled, smiled) for non-human subjects." },
  { id: 19, type: "multiple-choice", text: "Ethan's explanation of wind chimes demonstrates:", options: { choices: ["Only scientific knowledge", "Only creative thinking", "Both scientific knowledge and literary awareness", "Neither scientific nor literary concepts"] }, answer: "c", theme: "interdisciplinary", difficulty: "medium", tags: ["INTERDISCIPLINARY", "SCIENCE-ARTS CONNECTION", "CRITICAL THINKING", "COMPREHENSIVE ANALYSIS"], hints: ["Ethan talked about vibrations AND personification.", "He combined science with figurative language.", "The answer covers both areas."], explanation: "Ethan combined physics (vibrations/sound) with literary awareness (personification)." },
  { id: 20, type: "fill-blank", text: "When Ethan gave human qualities to the wind in his description, he was using the literary device called ____________.", options: {}, answer: "personification", theme: "language", difficulty: "easy", tags: ["LANGUAGE ARTS", "LITERARY DEVICES", "TERMINOLOGY RECALL", "READING STANDARDS"], hints: ["It starts with the letter P.", "It means treating non-human things as if they're human.", "Think: person + ification."], explanation: "Personification is attributing human characteristics to non-human things." },
  { id: 21, type: "multiple-choice", text: "If Ethan and his mother walked 2.8 miles in 45 minutes, what was their average speed?", options: { choices: ["3.7 mph", "2.5 mph", "4.2 mph", "1.9 mph"] }, answer: "a", theme: "math", difficulty: "medium", tags: ["MATHEMATICS", "RATE CALCULATION", "WORD PROBLEM", "PRACTICAL MATH"], hints: ["Speed = distance / time.", "Convert 45 minutes to hours first.", "45 minutes = 0.75 hours, then divide 2.8 by 0.75."], explanation: "Speed = 2.8 miles / 0.75 hours = 3.73 mph ≈ 3.7 mph." },
  { id: 22, type: "word-sequence", text: "Rearrange these words to form Ethan's explanation about triangular structures:", options: { wordSequence: ["STRONGEST", "TRIANGLES", "SHAPES", "ARE", "THE", "ONE OF", "BECAUSE", "THEY", "CAN", "HANDLE", "PRESSURE"] }, answer: ["TRIANGLES", "ARE", "ONE OF", "THE", "STRONGEST", "SHAPES", "BECAUSE", "THEY", "CAN", "HANDLE", "PRESSURE"], theme: "language", difficulty: "medium", tags: ["LANGUAGE ARTS", "SENTENCE STRUCTURE", "LOGICAL ORDERING", "READING COMPREHENSION"], hints: ["Start with the subject: TRIANGLES.", "The verb comes next: ARE.", "End with the reason: BECAUSE THEY CAN HANDLE PRESSURE."], explanation: "Triangles are one of the strongest shapes because they can handle pressure." },
  { id: 23, type: "multiple-choice", text: "If they maintained the same pace, how long would it take them to walk 1.5 miles to the park?", options: { choices: ["24 minutes", "30 minutes", "32 minutes", "45 minutes"] }, answer: "a", theme: "math", difficulty: "medium", tags: ["MATHEMATICS", "TIME CALCULATION", "PROPORTIONAL REASONING", "PRACTICAL APPLICATION"], hints: ["Their speed is about 3.7 mph.", "Time = distance / speed.", "1.5 / 3.73 × 60 ≈ 24 minutes."], explanation: "At 3.7 mph: time = 1.5/3.73 × 60 ≈ 24 minutes." },
  { id: 24, type: "multiple-choice", text: "Triangular roofs are common because:", options: { choices: ["Triangles are more attractive", "Rain or snow slides off easily and they're structurally strong", "They're cheaper to build", "They provide more attic space"] }, answer: "b", theme: "engineering", difficulty: "medium", tags: ["ENGINEERING", "STRUCTURAL DESIGN", "FUNCTIONAL REASONING", "PRACTICAL SCIENCE"], hints: ["Consider weather and structural factors.", "Sloped surfaces help with precipitation.", "Triangles resist deformation."], explanation: "Triangular roofs shed rain/snow and are structurally strong." },
  { id: 25, type: "multiple-choice", text: "Ethan's understanding of scientific concepts comes from:", options: { choices: ["Repeating memorized facts without understanding", "Trying to impress his mother", "Connecting classroom learning to real-world observations", "Reading about topics online"] }, answer: "c", theme: "interdisciplinary", difficulty: "medium", tags: ["LEARNING ASSESSMENT", "COGNITIVE DEVELOPMENT", "READING INFERENCE", "CHARACTER ANALYSIS"], hints: ["Ethan applies what he learned in school to the walk.", "He makes real-world connections.", "He connects theory to practice."], explanation: "Ethan demonstrates deep learning by connecting classroom concepts to real-world observations." },
  { id: 26, type: "multiple-choice", text: "Ethan's understanding of geometry is primarily based on:", options: { choices: ["Classroom instruction", "Real-world observations", "Reading scientific books", "Computer simulations"] }, answer: "b", theme: "interdisciplinary", difficulty: "hard", tags: ["READING ANALYSIS", "INFERENCE", "SAT PREPARATION", "TEXT INTERPRETATION"], hints: ["Think about where Ethan is learning.", "He's on a walk, not in a classroom.", "He observes shapes in his environment."], explanation: "The story shows Ethan learning geometry through observing shapes during his walk." },
  { id: 27, type: "multiple-choice", text: "What is the strongest evidence that Ethan enjoys sharing knowledge?", options: { choices: ["He asks his mother questions", "He eagerly explains concepts before she can respond", "He measures the distance they walked", "He wants to explore more places"] }, answer: "b", theme: "language", difficulty: "hard", tags: ["READING ANALYSIS", "EVIDENCE-BASED REASONING", "SAT PREPARATION", "CHARACTER ASSESSMENT"], hints: ["Look for actions that show enthusiasm.", "Eagerness to explain shows passion for sharing.", "He doesn't wait to be asked."], explanation: "Ethan eagerly explains concepts unprompted, showing enthusiasm for sharing knowledge." },
  { id: 28, type: "multiple-choice", text: "Potential energy is most directly related to:", options: { choices: ["Speed of movement", "Material composition", "Height above ground", "Air resistance"] }, answer: "c", theme: "science", difficulty: "medium", tags: ["PHYSICS", "CONCEPTUAL UNDERSTANDING", "SAT SCIENCE", "READING COMPREHENSION"], hints: ["Potential energy is about position.", "Higher up = more potential energy.", "Think gravitational potential energy."], explanation: "Gravitational potential energy is directly related to height above ground (PE = mgh)." },
  { id: 29, type: "multiple-choice", text: "When Ethan described wood as 'coarse' compared to metal, he most likely meant:", options: { choices: ["Flexible", "Rough-textured", "Waterproof", "Environmentally friendly"] }, answer: "b", theme: "language", difficulty: "medium", tags: ["VOCABULARY", "CONTEXTUAL MEANING", "SAT VERBAL", "WORD INTERPRETATION"], hints: ["Coarse is about texture.", "Think about touching wood vs. metal.", "It means rough, not smooth."], explanation: "'Coarse' means rough-textured, describing the feel of wood compared to smooth metal." },
  { id: 30, type: "multiple-choice", text: "The mother's attitude toward learning could best be described as:", options: { choices: ["Disinterested", "Encouraging curiosity", "Overly critical", "Solely focused on formal education"] }, answer: "b", theme: "language", difficulty: "medium", tags: ["CHARACTER ANALYSIS", "READING INFERENCE", "SAT READING", "TEXTUAL EVIDENCE"], hints: ["She supports Ethan's observations.", "She doesn't dismiss his explanations.", "She fosters his curiosity."], explanation: "The mother encourages Ethan's curiosity by engaging with his observations." },
  { id: 31, type: "fill-blank", text: "A roof is in the shape of a triangle with sides of 5m, 5m, and 8m. Its area is _________ square meters.", options: {}, answer: "12", theme: "math", difficulty: "hard", tags: ["GEOMETRY", "ADVANCED CALCULATION", "HERON'S FORMULA", "MATH COMPETITION"], hints: ["Use Heron's formula: s = (a+b+c)/2.", "s = (5+5+8)/2 = 9.", "Area = √(s(s-a)(s-b)(s-c)) = √(9×4×4×1) = 12."], explanation: "Using Heron's formula: s=9, Area = √(9×4×4×1) = 12 sq meters." },
  { id: 32, type: "multiple-choice", text: "If a rhombus has diagonals of 6 cm and 8 cm, what is its area?", options: { choices: ["24 cm²", "48 cm²", "14 cm²", "24 cm²"] }, answer: "a", theme: "math", difficulty: "hard", tags: ["GEOMETRY", "ADVANCED CALCULATION", "MATH OLYMPIAD", "AREA FORMULAS"], hints: ["Area of rhombus = (d1 × d2) / 2.", "Multiply the diagonals: 6 × 8 = 48.", "Divide by 2: 48 / 2 = 24."], explanation: "Area of rhombus = (d1 × d2)/2 = (6 × 8)/2 = 24 cm²." },
  { id: 33, type: "multiple-choice", text: "If Ethan weighs 35 kg and climbs a 20-meter hill, how much potential energy does he gain? (g ≈ 10 m/s²)", options: { choices: ["700 joules", "7,000 joules", "70 joules", "350 joules"] }, answer: "b", theme: "science", difficulty: "hard", tags: ["PHYSICS", "ENERGY CALCULATION", "SCIENCE OLYMPIAD", "FORMULA APPLICATION"], hints: ["PE = mass × gravity × height.", "PE = 35 × 10 × 20.", "Multiply all three numbers."], explanation: "PE = mgh = 35 × 10 × 20 = 7,000 joules." },
  { id: 34, type: "multiple-choice", text: "Potential energy is to height as kinetic energy is to:", options: { choices: ["Weight", "Velocity", "Mass", "Temperature"] }, answer: "b", theme: "science", difficulty: "medium", tags: ["PHYSICS", "ANALOGICAL REASONING", "CONCEPTUAL RELATIONSHIPS", "SCIENCE APPLICATION"], hints: ["PE depends on height.", "KE depends on movement.", "Movement speed is called..."], explanation: "PE depends on height; KE depends on velocity (speed)." },
  { id: 35, type: "multiple-choice", text: "Which shape does NOT belong in this group?", options: { choices: ["Rhombus", "Diamond", "Rectangle", "Quadrilateral"] }, answer: "c", theme: "math", difficulty: "medium", tags: ["GEOMETRY", "CLASSIFICATION", "LOGICAL REASONING", "CATEGORY EXCLUSION"], hints: ["Rhombus, diamond, and quadrilateral all have equal opposite sides.", "A rectangle has right angles.", "Which one has a different property from the others?"], explanation: "A rectangle has right angles while rhombus/diamond are specific quadrilaterals with equal sides." },
  { id: 36, type: "hidden-word", text: "Find five material properties Ethan discussed in this word search:", options: { grid: ["TRANSPARENTA", "DFGHJKLCXZA", "QWERTYUIOAS", "ABFLEXIBLER", "SDFGHJKLZAE", "BZXCVBNMQWE", "LIGHTWEIGHTT", "ERTYUIOPQWE"], words: ["TRANSPARENT", "FLEXIBLE", "LIGHTWEIGHT", "DURABLE", "COARSE"] }, answer: ["TRANSPARENT", "FLEXIBLE", "LIGHTWEIGHT", "DURABLE", "COARSE"], theme: "materials", difficulty: "medium", tags: ["MATERIALS SCIENCE", "PROPERTY VOCABULARY", "VISUAL SCANNING", "SCIENCE TERMINOLOGY"], hints: ["Look in the first row for TRANSPARENT.", "FLEXIBLE is in row 4.", "LIGHTWEIGHT is in row 7."], explanation: "The five material properties are Transparent, Flexible, Lightweight, Durable, and Coarse." },
  { id: 37, type: "multiple-choice", text: "Understanding geometry is useful in everyday life because:", options: { choices: ["It helps with calculating large numbers", "It improves spelling abilities", "It helps recognize patterns and solve spatial problems", "It's only useful for architects and engineers"] }, answer: "c", theme: "math", difficulty: "medium", tags: ["PRACTICAL GEOMETRY", "REAL-WORLD APPLICATION", "CRITICAL THINKING", "STEM REASONING"], hints: ["Geometry is about shapes and space.", "We encounter shapes every day.", "Pattern recognition and spatial thinking are key."], explanation: "Geometry helps recognize patterns and solve spatial problems in daily life." },
  { id: 38, type: "unscramble", text: "Unscramble these material properties mentioned in the story:", options: { letters: "LEBARDU,PARTSTANERN,SESSLITRE,SEACOR" }, answer: ["DURABLE", "TRANSPARENT", "RESILIENT", "COARSE"], theme: "materials", difficulty: "medium", tags: ["MATERIALS SCIENCE", "DESCRIPTIVE VOCABULARY", "SPELLING", "PROPERTY TERMINOLOGY"], hints: ["The first word means long-lasting.", "The second word means see-through.", "The fourth word means rough."], explanation: "Durable, Transparent, Resilient, and Coarse are material properties." },
  { id: 39, type: "multiple-choice", text: "Ethan jogged downhill at 6 mph for 0.4 miles. How many minutes did that take?", options: { choices: ["2 minutes", "4 minutes", "6 minutes", "24 minutes"] }, answer: "b", theme: "math", difficulty: "medium", tags: ["MATH", "SPEED/TIME", "CALCULATION", "PRACTICAL APPLICATION"], hints: ["Time = distance / speed.", "0.4 / 6 = hours.", "Convert to minutes by multiplying by 60."], explanation: "Time = 0.4/6 hours = 0.0667 hours × 60 = 4 minutes." },
  { id: 40, type: "multiple-choice", text: "What kind of energy does the wind transfer to the chimes to create sound?", options: { choices: ["Chemical energy", "Nuclear energy", "Mechanical energy", "Thermal energy"] }, answer: "c", theme: "science", difficulty: "easy", tags: ["SCIENCE", "ENERGY TRANSFER", "CONCEPTUAL UNDERSTANDING", "PHYSICS"], hints: ["Wind is moving air.", "Moving things have mechanical energy.", "The wind physically moves the chimes."], explanation: "Wind transfers mechanical energy to the chimes, causing them to vibrate and create sound." },
  { id: 41, type: "matching", text: "Match each object with its shape:", options: { items: [{ item: "Stop sign", match: "Octagon" }, { item: "School zone sign", match: "Pentagon" }, { item: "Roof", match: "Triangle" }, { item: "Construction sign", match: "Diamond" }] }, answer: ["Stop sign:Octagon", "School zone sign:Pentagon", "Roof:Triangle", "Construction sign:Diamond"], theme: "math", difficulty: "medium", tags: ["MATH", "SHAPES", "RECOGNITION", "REAL-WORLD APPLICATION"], hints: ["Stop signs have 8 sides.", "School zone signs have 5 sides.", "Roofs are triangular."], explanation: "Stop sign=Octagon, School zone=Pentagon, Roof=Triangle, Construction=Diamond." },
  { id: 42, type: "multiple-choice", text: "If Ethan walked 2.8 miles and took 5600 steps, what is his average stride length in feet? (1 mile = 5280 ft)", options: { choices: ["2.6 feet", "2.5 feet", "3.0 feet", "1.5 feet"] }, answer: "a", theme: "math", difficulty: "hard", tags: ["MATH", "DISTANCE", "MEASUREMENT", "CONVERSION"], hints: ["First convert miles to feet: 2.8 × 5280.", "Then divide total feet by number of steps.", "2.8 × 5280 = 14,784 feet / 5600 steps."], explanation: "2.8 miles = 14,784 feet. 14,784 / 5600 = 2.64 feet ≈ 2.6 feet." },
  { id: 43, type: "true-false", text: "Ethan claimed that a diagonal splits a rhombus into two congruent triangles.", options: {}, answer: "true", theme: "math", difficulty: "medium", tags: ["GEOMETRY", "SHAPE PROPERTIES", "SPATIAL REASONING", "MATH FACTS"], hints: ["Think about what happens when you draw a diagonal.", "Congruent means same shape and size.", "A rhombus diagonal does create equal halves."], explanation: "A diagonal of a rhombus does indeed split it into two congruent triangles." },
  { id: 44, type: "multiple-choice", text: "If you split a rhombus along its diagonal, what do you get?", options: { choices: ["Two rectangles", "Two triangles", "Four triangles", "Two trapezoids"] }, answer: "b", theme: "math", difficulty: "medium", tags: ["GEOMETRY", "SHAPE DECOMPOSITION", "SPATIAL REASONING", "MATHEMATICAL VISUALIZATION"], hints: ["A diagonal goes from corner to corner.", "It divides the shape into two parts.", "Each part is a three-sided figure."], explanation: "A diagonal splits a rhombus into two congruent triangles." },
  { id: 45, type: "multiple-choice", text: "Air is to wind as water is to:", options: { choices: ["Rain", "Current", "Steam", "Ice"] }, answer: "b", theme: "language", difficulty: "medium", tags: ["ANALOGICAL REASONING", "CONCEPTUAL RELATIONSHIPS", "LOGICAL THINKING", "VERBAL REASONING"], hints: ["Wind is air in motion.", "What is water in motion called?", "Think about rivers and oceans."], explanation: "Wind is moving air; current is moving water." },
  { id: 46, type: "multiple-choice", text: "To create a descending musical scale with wind chime tubes, arrange them:", options: { choices: ["Shortest to longest", "Longest to shortest", "Random arrangement", "Alternating long and short"] }, answer: "b", theme: "interdisciplinary", difficulty: "medium", tags: ["MUSIC PHYSICS", "SOUND PROPERTIES", "APPLICATION THINKING", "INTERDISCIPLINARY"], hints: ["Longer tubes make lower sounds.", "Descending means going from high to low pitch.", "Start with the tube that makes the highest sound."], explanation: "Longest tubes make the lowest pitch; arrange longest to shortest for a descending scale." },
  { id: 47, type: "multiple-choice", text: "The primary reason triangles are used in construction is:", options: { choices: ["They use less material than other shapes", "They're more aesthetically pleasing", "They maintain their shape under pressure", "They're easier to manufacture"] }, answer: "c", theme: "engineering", difficulty: "medium", tags: ["ENGINEERING", "STRUCTURAL PRINCIPLES", "DESIGN REASONING", "APPLIED GEOMETRY"], hints: ["Triangles are rigid.", "They don't deform under load.", "Shape maintenance under pressure is the key."], explanation: "Triangles maintain their shape under pressure, making them ideal for structural use." },
  { id: 48, type: "hidden-word", text: "Find these energy-related terms in the grid:", options: { grid: ["POTENTIALGT", "SDCVIBRATEB", "KFGHJKINETIH", "LDFGHRESIQW", "FORCEZXERTY", "SOUNDMNBCVZ", "MOMENTUM123", "FRICTIONSDF"], words: ["POTENTIAL", "KINETIC", "FORCE", "SOUND", "VIBRATE", "FRICTION", "MOMENTUM"] }, answer: ["POTENTIAL", "KINETIC", "FORCE", "SOUND", "VIBRATE", "FRICTION", "MOMENTUM"], theme: "science", difficulty: "medium", tags: ["PHYSICS", "ENERGY TERMS", "VOCABULARY", "SCIENTIFIC CONCEPTS"], hints: ["Look for POTENTIAL in row 1.", "KINETIC is in row 3.", "FRICTION is in the last row."], explanation: "The seven energy terms are Potential, Kinetic, Force, Sound, Vibrate, Friction, Momentum." },
  { id: 49, type: "multiple-choice", text: "What does Ethan mean when he says the wind has a personality?", options: { choices: ["The wind is alive", "He's using personification to describe the wind's variable nature", "He believes wind has consciousness", "He's confused about scientific concepts"] }, answer: "b", theme: "language", difficulty: "medium", tags: ["LANGUAGE ARTS", "FIGURATIVE LANGUAGE", "READING COMPREHENSION", "LITERARY ANALYSIS"], hints: ["This is figurative, not literal.", "Ethan is using a literary device.", "Giving personality to wind is personification."], explanation: "Ethan uses personification to describe how wind behaves differently at different times." },
];

export async function seed() {
  // Check if already seeded
  const existingStories = await db.select().from(stories);
  if (existingStories.length > 0) {
    console.log("Database already seeded, skipping.");
    return;
  }

  console.log("Seeding database...");

  // Create story
  const [story] = await db
    .insert(stories)
    .values({
      title: "A Walk to Remember",
      description:
        "Join Ethan and his mother on a neighborhood walk where everyday observations become exciting lessons in geometry, physics, materials science, and language arts!",
      gradeLevel: 4,
      totalChapters: 4,
      imageUrl: null,
    })
    .returning();

  // Create chapters
  const chapterContents = [
    {
      number: 1,
      title: "Setting Out",
      content: `Ethan pulled on his sneakers and ran to the front door. "Mom, are you ready for our walk?" he called out excitedly.\n\nHis mother smiled and grabbed her hat. "Let's go explore the neighborhood!"\n\nAs they stepped outside, Ethan immediately noticed the bright red stop sign at the corner. "Mom, did you know stop signs are octagons? That means they have eight sides!"\n\n"That's right!" his mother replied. "Why do you think they chose that shape?"\n\nEthan thought for a moment. "I think it's because the octagon shape is so unique that you can recognize it even from the back, or when it's partially covered by snow!"\n\nThey walked past several houses, and Ethan pointed up at the rooftops. "See those triangular roofs, Mom? Triangles are one of the strongest shapes in construction. Rain and snow slide right off them, and they can handle a lot of pressure without collapsing."`,
    },
    {
      number: 2,
      title: "The Hill",
      content: `As they approached a small hill, Ethan started explaining about energy. "Mom, when I stand at the top of this hill, I have potential energy because of my height. It's like stored energy!"\n\nHis mother nodded. "And what happens when you go down?"\n\n"The potential energy transforms into kinetic energy — that's the energy of motion!" Ethan started jogging down the hill to demonstrate. "See? I'm converting potential energy into kinetic energy right now!"\n\nHe picked up a small rock at the top of the hill. "If I put this rock here, it has potential energy. When it rolls down..." He gently placed the rock on the slope and watched it roll. "There it goes! Potential energy becoming kinetic energy!"\n\n"That's the law of conservation of energy," his mother added. "Energy isn't created or destroyed, it just changes form."`,
    },
    {
      number: 3,
      title: "Wind and Sound",
      content: `A strong gust of wind pushed against them as they continued walking. Ethan leaned into it, laughing. "Feel that, Mom? That's air resistance! The wind is pushing against us."\n\nThey passed a house with wind chimes on the porch. The chimes tinkled softly in the breeze.\n\n"Listen to that!" Ethan said. "The wind transfers mechanical energy to the chimes. When they vibrate, they create sound waves that we can hear."\n\n"The wind is playing us a song," his mother smiled.\n\nEthan grinned. "That's personification, Mom! Giving the wind human qualities like playing music. But scientifically, longer tubes make lower sounds and shorter tubes make higher sounds. So if you arranged them from longest to shortest, you'd get a descending scale!"`,
    },
    {
      number: 4,
      title: "Materials and Reflections",
      content: `Near the construction site, Ethan noticed different materials everywhere. "Mom, look at that construction warning sign — it's shaped like a rhombus, or a diamond shape! Did you know if you draw a diagonal through a rhombus, it splits into two equal triangles?"\n\nHe knelt down and drew a rhombus in the dirt with a stick, then added a diagonal line. "See? Two congruent triangles!"\n\nThey examined a stop sign up close. "This is made of metal because it's more durable than wood," Ethan explained. "Wood is coarse and would deteriorate in rain. Metal is weather-resistant and can stay outdoors for years."\n\n"You're really observant," his mother said.\n\nAs they headed home, Ethan calculated their walk. "We walked 2.8 miles in 45 minutes. That means our average speed was about 3.7 miles per hour! At that pace, it would take us only 24 minutes to walk to the park, which is 1.5 miles away."\n\nHis mother hugged him. "Every walk with you is an adventure in learning, Ethan."`,
    },
  ];

  for (const ch of chapterContents) {
    const [chapter] = await db
      .insert(chapters)
      .values({
        storyId: story.id,
        chapterNumber: ch.number,
        title: ch.title,
        content: ch.content,
      })
      .returning();

    // Only seed questions for chapter 4 (our question dataset)
    if (ch.number === 4) {
      for (const q of questionData) {
        await db.insert(questions).values({
          chapterId: chapter.id,
          type: q.type,
          text: q.text,
          options: q.options,
          answer: q.answer,
          bloomLevel: bloomMap[q.id] || "understand",
          difficulty: q.difficulty,
          theme: q.theme,
          tags: q.tags,
          hints: q.hints,
          explanation: q.explanation,
        });
      }
      console.log(`Seeded ${questionData.length} questions for Chapter 4.`);
    }
  }

  console.log("Seeding complete!");
}
